
  // Hebrides
  { name: "Breachacha Castle (Main)", lat: 56.548, lng: -6.878, country: "Scotland", type: "castle", era: "14th century", condition: "restored", description: "MacLean castle on Coll.", image: "", rating: 3.6, reviewCount: 38, county: "Argyll and Bute", tags: ["hidden-gem"], access: "restricted" },
  { name: "Coeffin Castle (Main)", lat: 56.548, lng: -6.198, country: "Scotland", type: "castle", era: "13th century", condition: "ruin", description: "MacDougall castle ruin on Lismore.", image: "", rating: 3.4, reviewCount: 22, county: "Argyll and Bute", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mingary Castle (Main)", lat: 56.685, lng: -6.098, country: "Scotland", type: "castle", era: "13th century", condition: "restored", description: "Restored MacIain castle on the Ardnamurchan coast.", image: "", rating: 3.8, reviewCount: 68, county: "Highland", tags: ["dramatic-ruin", "coastal"], access: "paid" },
  { name: "Borve Castle (Harris)", lat: 57.798, lng: -6.962, country: "Scotland", type: "tower house", era: "16th century", condition: "ruin", description: "MacLeod tower house on Harris.", image: "", rating: 3.4, reviewCount: 22, county: "Western Isles", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Dun Carloway Broch", lat: 58.278, lng: -6.788, country: "Scotland", type: "broch", era: "Iron Age", condition: "ruin", description: "Dramatic Iron Age broch on Lewis.", image: "", rating: 4.1, reviewCount: 155, county: "Western Isles", tags: ["must-see", "free"], access: "free" },
  { name: "Amhuinnsuidhe Castle", lat: 57.888, lng: -6.968, country: "Scotland", type: "castle", era: "19th century", condition: "intact", description: "Victorian castle on North Harris.", image: "", rating: 3.5, reviewCount: 28, county: "Western Isles", tags: ["hidden-gem"], access: "restricted" },

  // Highland extras
  { name: "Castle Stuart (Main)", lat: 57.522, lng: -4.088, country: "Scotland", type: "tower house", era: "17th century", condition: "restored", description: "Restored tower house near Inverness, now a hotel.", image: "", rating: 3.7, reviewCount: 52, county: "Highland", tags: ["hidden-gem"], access: "paid" },
  { name: "Beaufort Castle (Main)", lat: 57.408, lng: -4.488, country: "Scotland", type: "castle", era: "19th century", condition: "intact", description: "Seat of the Frasers of Lovat.", image: "", rating: 3.3, reviewCount: 18, county: "Highland", tags: ["hidden-gem"], access: "restricted" },
  { name: "Invergarry Castle (Main)", lat: 57.058, lng: -4.978, country: "Scotland", type: "tower house", era: "17th century", condition: "ruin", description: "MacDonell stronghold on Loch Oich.", image: "", rating: 3.5, reviewCount: 30, county: "Highland", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tioram Castle (Main)", lat: 56.775, lng: -5.832, country: "Scotland", type: "castle", era: "13th century", condition: "ruin", description: "Clanranald castle on a tidal island in Loch Moidart.", image: "", rating: 4.0, reviewCount: 130, county: "Highland", tags: ["must-see", "free", "coastal"], access: "free" },
  { name: "Kinlochaline Castle (Main)", lat: 56.578, lng: -5.758, country: "Scotland", type: "tower house", era: "15th century", condition: "restored", description: "Restored MacInnes tower house on Loch Aline.", image: "", rating: 3.4, reviewCount: 22, county: "Highland", tags: ["hidden-gem"], access: "restricted" },
  { name: "Dunbeath Castle (Main)", lat: 58.248, lng: -3.428, country: "Scotland", type: "castle", era: "15th century", condition: "intact", description: "Castle on a promontory near Dunbeath.", image: "", rating: 3.3, reviewCount: 18, county: "Highland", tags: ["hidden-gem"], access: "restricted" },
  { name: "Girnigoe Castle (Ruins)", lat: 58.442, lng: -3.068, country: "Scotland", type: "castle", era: "15th century", condition: "ruin", description: "Dramatic Sinclair castle ruins on sea cliffs.", image: "", rating: 3.9, reviewCount: 95, county: "Highland", tags: ["dramatic-ruin", "free", "coastal"], access: "free" },
  { name: "Skelbo Castle (Main)", lat: 57.908, lng: -4.018, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Sutherland castle overlooking Loch Fleet.", image: "", rating: 3.3, reviewCount: 18, county: "Highland", tags: ["hidden-gem", "free"], access: "free" },

  // Fife extras
  { name: "Kellie Castle (Main)", lat: 56.328, lng: -2.788, country: "Scotland", type: "castle", era: "14th century", condition: "restored", description: "NTS castle with fine plaster ceilings.", image: "", rating: 3.8, reviewCount: 72, county: "Fife", tags: ["hidden-gem"], access: "paid" },
  { name: "Scotstarvit Tower (Main)", lat: 56.298, lng: -2.928, country: "Scotland", type: "tower house", era: "16th century", condition: "intact", description: "Tall tower house near Cupar.", image: "", rating: 3.4, reviewCount: 22, county: "Fife", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Macduff's Castle (Main)", lat: 56.215, lng: -3.058, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Wemyss castle ruin on the Fife coast.", image: "", rating: 3.3, reviewCount: 18, county: "Fife", tags: ["hidden-gem", "free", "coastal"], access: "free" },
  { name: "Lochore Castle", lat: 56.148, lng: -3.358, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Castle ruin on an island in Loch Ore.", image: "", rating: 3.2, reviewCount: 14, county: "Fife", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Balwearie Castle (Main)", lat: 56.188, lng: -3.218, country: "Scotland", type: "tower house", era: "15th century", condition: "ruin", description: "Scott tower house near Kirkcaldy.", image: "", rating: 3.1, reviewCount: 10, county: "Fife", tags: ["hidden-gem", "free"], access: "free" },

  // Ayrshire extras
  { name: "Dundonald Castle (Main)", lat: 55.578, lng: -4.548, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Royal Stewart castle with impressive tower.", image: "", rating: 3.7, reviewCount: 52, county: "Ayrshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Greenan Castle (Main)", lat: 55.428, lng: -4.668, country: "Scotland", type: "tower house", era: "16th century", condition: "ruin", description: "Dramatic clifftop tower near Ayr.", image: "", rating: 3.6, reviewCount: 40, county: "Ayrshire", tags: ["dramatic-ruin", "free", "coastal"], access: "free" },
  { name: "Dalquharran Castle (Main)", lat: 55.288, lng: -4.718, country: "Scotland", type: "castle", era: "18th century", condition: "ruin", description: "Robert Adam castle ruin near Dailly.", image: "", rating: 3.4, reviewCount: 22, county: "Ayrshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Maybole Castle (Main)", lat: 55.352, lng: -4.682, country: "Scotland", type: "tower house", era: "16th century", condition: "restored", description: "Kennedy townhouse in Maybole.", image: "", rating: 3.5, reviewCount: 28, county: "Ayrshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Loch Doon Castle", lat: 55.298, lng: -4.378, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Eleven-sided castle relocated from island to shore.", image: "", rating: 3.6, reviewCount: 38, county: "Ayrshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Rowallan Castle", lat: 55.612, lng: -4.508, country: "Scotland", type: "castle", era: "13th century", condition: "ruin", description: "Mure castle near Kilmaurs.", image: "", rating: 3.3, reviewCount: 16, county: "Ayrshire", tags: ["hidden-gem", "free"], access: "free" },

  // Lanarkshire/Central
  { name: "Cadzow Castle (Main)", lat: 55.758, lng: -4.038, country: "Scotland", type: "castle", era: "16th century", condition: "ruin", description: "Hamilton castle in Chatelherault Country Park.", image: "", rating: 3.6, reviewCount: 40, county: "Lanarkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Crookston Castle (Main)", lat: 55.838, lng: -4.358, country: "Scotland", type: "castle", era: "15th century", condition: "ruin", description: "Stewart castle in south Glasgow.", image: "", rating: 3.5, reviewCount: 30, county: "Lanarkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mugdock Castle (Main)", lat: 55.958, lng: -4.318, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Graham castle in Mugdock Country Park.", image: "", rating: 3.5, reviewCount: 30, county: "Stirlingshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Menstrie Castle (Main)", lat: 56.148, lng: -3.858, country: "Scotland", type: "tower house", era: "16th century", condition: "restored", description: "Nova Scotia Baronets memorial.", image: "", rating: 3.3, reviewCount: 18, county: "Clackmannanshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Clackmannan Tower (Main)", lat: 56.108, lng: -3.748, country: "Scotland", type: "tower house", era: "14th century", condition: "ruin", description: "Bruce tower house overlooking the Forth.", image: "", rating: 3.4, reviewCount: 22, county: "Clackmannanshire", tags: ["hidden-gem", "free"], access: "free" },

  // ===== WALES =====
  // Pembrokeshire extras
  { name: "Roch Castle", lat: 51.858, lng: -5.098, country: "Wales", type: "castle", era: "12th century", condition: "restored", description: "Norman castle on a rocky outcrop, now a luxury hotel.", image: "", rating: 3.7, reviewCount: 52, county: "Pembrokeshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Upton Castle", lat: 51.735, lng: -4.898, country: "Wales", type: "castle", era: "13th century", condition: "intact", description: "Medieval castle with fine gardens.", image: "", rating: 3.5, reviewCount: 28, county: "Pembrokeshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Benton Castle", lat: 51.738, lng: -4.922, country: "Wales", type: "castle", era: "13th century", condition: "intact", description: "Privately owned castle near Milford Haven.", image: "", rating: 3.2, reviewCount: 12, county: "Pembrokeshire", tags: ["hidden-gem"], access: "restricted" },
  { name: "Wolf's Castle Mound", lat: 51.895, lng: -4.978, country: "Wales", type: "motte", era: "12th century", condition: "intact", description: "Norman motte near Wolf's Castle village.", image: "", rating: 3.0, reviewCount: 8, county: "Pembrokeshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tenby Castle (Main)", lat: 51.672, lng: -4.698, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Castle remains on Castle Hill overlooking Tenby harbour.", image: "", rating: 3.5, reviewCount: 32, county: "Pembrokeshire", tags: ["hidden-gem", "free", "coastal"], access: "free" },
  { name: "Angle Tower (Main)", lat: 51.680, lng: -5.098, country: "Wales", type: "tower house", era: "14th century", condition: "ruin", description: "Rare Welsh tower house near Angle village.", image: "", rating: 3.4, reviewCount: 22, county: "Pembrokeshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Nevern Castle", lat: 51.998, lng: -4.768, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle ruin near Nevern.", image: "", rating: 3.4, reviewCount: 22, county: "Pembrokeshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Castell Henllys", lat: 52.015, lng: -4.728, country: "Wales", type: "hillfort", era: "Iron Age", condition: "reconstructed", description: "Reconstructed Iron Age fort with roundhouses.", image: "", rating: 4.0, reviewCount: 125, county: "Pembrokeshire", tags: ["must-see"], access: "paid" },
  { name: "Newport Castle (Pembs Main)", lat: 52.018, lng: -4.838, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Norman castle in Newport, Pembrokeshire.", image: "", rating: 3.3, reviewCount: 18, county: "Pembrokeshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Llansteffan Castle (Main)", lat: 51.768, lng: -4.388, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Hilltop castle overlooking the Towy estuary.", image: "", rating: 3.8, reviewCount: 72, county: "Carmarthenshire", tags: ["dramatic-ruin", "free", "coastal"], access: "free" },

  // Carmarthenshire extras
  { name: "Dryslwyn Castle (Main)", lat: 51.858, lng: -4.028, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Welsh-built castle on a hilltop above the Towy.", image: "", rating: 3.7, reviewCount: 52, county: "Carmarthenshire", tags: ["dramatic-ruin", "free"], access: "free" },
  { name: "Dinefwr Castle (Main)", lat: 51.868, lng: -3.998, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Seat of the Kingdom of Deheubarth in Dinefwr Park.", image: "", rating: 3.9, reviewCount: 95, county: "Carmarthenshire", tags: ["must-see"], access: "paid" },
  { name: "Newcastle Emlyn Castle (Main)", lat: 52.038, lng: -4.468, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Castle ruin above the River Teifi.", image: "", rating: 3.5, reviewCount: 32, county: "Carmarthenshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Llandovery Castle", lat: 51.995, lng: -3.798, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle mound in Llandovery.", image: "", rating: 3.3, reviewCount: 18, county: "Carmarthenshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Aberglasney House (Main)", lat: 51.868, lng: -4.038, country: "Wales", type: "country house", era: "16th century", condition: "restored", description: "Historic house and gardens in the Towy Valley.", image: "", rating: 4.1, reviewCount: 160, county: "Carmarthenshire", tags: ["must-see"], access: "paid" },

  // Ceredigion extras
  { name: "Cardigan Castle (Main)", lat: 52.082, lng: -4.658, country: "Wales", type: "castle", era: "12th century", condition: "restored", description: "Norman castle where the first eisteddfod was held.", image: "", rating: 3.8, reviewCount: 72, county: "Ceredigion", tags: ["must-see"], access: "paid" },
  { name: "Tregaron Castle Mound (Main)", lat: 52.218, lng: -3.938, country: "Wales", type: "motte", era: "12th century", condition: "intact", description: "Norman motte in Tregaron town.", image: "", rating: 3.0, reviewCount: 8, county: "Ceredigion", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Castell Abereinion", lat: 52.358, lng: -3.718, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Native Welsh castle earthworks.", image: "", rating: 3.1, reviewCount: 10, county: "Ceredigion", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Castell Gwallter", lat: 52.258, lng: -4.058, country: "Wales", type: "motte", era: "12th century", condition: "intact", description: "Motte and bailey near Llanfihangel.", image: "", rating: 3.0, reviewCount: 7, county: "Ceredigion", tags: ["hidden-gem", "free"], access: "free" },

  // Powys extras
  { name: "Hay Castle (Main)", lat: 52.072, lng: -3.128, country: "Wales", type: "castle", era: "12th century", condition: "restored", description: "Castle in the famous book town, recently restored.", image: "", rating: 3.8, reviewCount: 72, county: "Powys", tags: ["must-see"], access: "paid" },
  { name: "Bronllys Castle (Main)", lat: 51.978, lng: -3.238, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Round keep on a motte near Bronllys.", image: "", rating: 3.4, reviewCount: 22, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Castell Collen (Main)", lat: 52.248, lng: -3.548, country: "Wales", type: "Roman fort", era: "Roman", condition: "ruin", description: "Roman auxiliary fort near Llandrindod Wells.", image: "", rating: 3.3, reviewCount: 18, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Painscastle (Main)", lat: 52.108, lng: -3.238, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Motte and bailey earthworks, scene of famous battle.", image: "", rating: 3.2, reviewCount: 14, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Dolforwyn Castle (Main)", lat: 52.518, lng: -3.348, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Last castle built by a native Welsh prince.", image: "", rating: 3.7, reviewCount: 52, county: "Powys", tags: ["dramatic-ruin", "free"], access: "free" },
  { name: "Aberedw Castle", lat: 52.128, lng: -3.348, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Castle where Llywelyn ap Gruffudd may have spent his last night.", image: "", rating: 3.3, reviewCount: 16, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Cefnllys Castle", lat: 52.268, lng: -3.348, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Mortimer castle ruins on a dramatic hilltop.", image: "", rating: 3.5, reviewCount: 28, county: "Powys", tags: ["dramatic-ruin", "hidden-gem", "free"], access: "free" },
  { name: "Bleddfa Castle", lat: 52.318, lng: -3.148, country: "Wales", type: "motte", era: "12th century", condition: "intact", description: "Norman motte on the Marches.", image: "", rating: 3.0, reviewCount: 7, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Knighton Castle", lat: 52.348, lng: -3.048, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Mortimer castle mound in Knighton.", image: "", rating: 3.1, reviewCount: 10, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mathrafal Castle", lat: 52.668, lng: -3.408, country: "Wales", type: "castle", era: "11th century", condition: "ruin", description: "Seat of the Princes of Powys, mostly earthworks.", image: "", rating: 3.4, reviewCount: 20, county: "Powys", tags: ["hidden-gem", "free"], access: "free" },

  // Gwent extras
  { name: "Abergavenny Castle (Main)", lat: 51.822, lng: -3.018, country: "Wales", type: "castle", era: "11th century", condition: "ruin", description: "Norman castle with museum in the keep.", image: "", rating: 3.5, reviewCount: 32, county: "Monmouthshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Usk Castle (Main)", lat: 51.702, lng: -2.898, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle ruin with gardens, privately owned.", image: "", rating: 3.5, reviewCount: 30, county: "Monmouthshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Caldicot Castle (Main)", lat: 51.588, lng: -2.758, country: "Wales", type: "castle", era: "12th century", condition: "restored", description: "Norman castle restored in Victorian era.", image: "", rating: 3.7, reviewCount: 55, county: "Monmouthshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Penhow Castle", lat: 51.598, lng: -2.878, country: "Wales", type: "castle", era: "12th century", condition: "intact", description: "Claimed as the oldest lived-in castle in Wales.", image: "", rating: 3.4, reviewCount: 22, county: "Monmouthshire", tags: ["hidden-gem"], access: "restricted" },

  // North Wales extras
  { name: "Castell Aberlleiniog (Main)", lat: 53.278, lng: -4.078, country: "Wales", type: "castle", era: "11th century", condition: "ruin", description: "Norman motte and bailey on Anglesey.", image: "", rating: 3.3, reviewCount: 18, county: "Anglesey", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tomen y Mur (Main)", lat: 52.868, lng: -3.878, country: "Wales", type: "Roman fort", era: "Roman", condition: "ruin", description: "Roman fort with Norman motte.", image: "", rating: 3.5, reviewCount: 28, county: "Gwynedd", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Deganwy Castle (Main)", lat: 53.288, lng: -3.828, country: "Wales", type: "castle", era: "6th century", condition: "ruin", description: "Twin-peaked castle site with panoramic views of Conwy.", image: "", rating: 3.5, reviewCount: 30, county: "Conwy", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Caergwrle Castle (Main)", lat: 53.098, lng: -3.058, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Native Welsh castle near Caergwrle.", image: "", rating: 3.3, reviewCount: 18, county: "Flintshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Hawarden Castle Old", lat: 53.182, lng: -3.028, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Medieval castle ruins in Hawarden Park.", image: "", rating: 3.4, reviewCount: 22, county: "Flintshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Ewloe Castle (Main)", lat: 53.178, lng: -3.058, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Hidden Welsh castle in woodland, built by Llywelyn ap Gruffudd.", image: "", rating: 3.6, reviewCount: 42, county: "Flintshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Dinas Emrys", lat: 53.028, lng: -4.058, country: "Wales", type: "hillfort", era: "Iron Age", condition: "ruin", description: "Legendary fortress associated with Vortigern and Merlin.", image: "", rating: 3.8, reviewCount: 68, county: "Gwynedd", tags: ["dramatic-ruin", "hidden-gem", "free"], access: "free" },
  { name: "Dolbadarn Castle (Main)", lat: 53.118, lng: -4.108, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Welsh prince's round-towered castle by Llyn Padarn.", image: "", rating: 3.8, reviewCount: 75, county: "Gwynedd", tags: ["dramatic-ruin", "free"], access: "free" },
  { name: "Castell Prysor", lat: 52.848, lng: -3.848, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Remote Welsh castle earthworks in Trawsfynydd.", image: "", rating: 3.1, reviewCount: 10, county: "Gwynedd", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Castell Carndochan", lat: 52.828, lng: -3.748, country: "Wales", type: "castle", era: "13th century", condition: "ruin", description: "Welsh prince's castle near Llanuwchllyn.", image: "", rating: 3.2, reviewCount: 12, county: "Gwynedd", tags: ["hidden-gem", "free"], access: "free" },

  // South Wales extras
  { name: "Oystermouth Castle (Main)", lat: 51.578, lng: -3.978, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle overlooking Swansea Bay.", image: "", rating: 3.6, reviewCount: 42, county: "Swansea", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Pennard Castle (Main)", lat: 51.568, lng: -4.068, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Romantic ruin overlooking Three Cliffs Bay.", image: "", rating: 3.9, reviewCount: 92, county: "Swansea", tags: ["dramatic-ruin", "free", "coastal"], access: "free" },
  { name: "Oxwich Castle (Main)", lat: 51.558, lng: -4.148, country: "Wales", type: "castle", era: "16th century", condition: "ruin", description: "Tudor mansion ruin on the Gower.", image: "", rating: 3.5, reviewCount: 30, county: "Swansea", tags: ["hidden-gem"], access: "paid" },
  { name: "Loughor Castle (Main)", lat: 51.668, lng: -4.068, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle on Roman fort site.", image: "", rating: 3.2, reviewCount: 14, county: "Swansea", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Newcastle (Bridgend Main)", lat: 51.508, lng: -3.578, country: "Wales", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle with fine Romanesque gateway.", image: "", rating: 3.5, reviewCount: 30, county: "Bridgend", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Fonmon Castle (Main)", lat: 51.398, lng: -3.448, country: "Wales", type: "castle", era: "12th century", condition: "intact", description: "One of the few inhabited medieval castles in Wales.", image: "", rating: 3.5, reviewCount: 28, county: "Vale of Glamorgan", tags: ["hidden-gem"], access: "paid" },
  { name: "Castell Coch Interior (Main)", lat: 51.532, lng: -3.255, country: "Wales", type: "castle", era: "19th century", condition: "restored", description: "Victorian Gothic Revival fantasy castle.", image: "", rating: 4.2, reviewCount: 210, county: "Cardiff", tags: ["must-see"], access: "paid" },

  // ===== ENGLAND =====
  // Yorkshire extras
  { name: "Spofforth Castle (Main)", lat: 53.948, lng: -1.458, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Percy family fortified manor.", image: "", rating: 3.4, reviewCount: 22, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Harewood Castle (Main)", lat: 53.898, lng: -1.548, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Aldburgh castle ruin in Harewood estate.", image: "", rating: 3.3, reviewCount: 18, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Sandal Castle (Main)", lat: 53.658, lng: -1.488, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "York castle where Richard of York was killed in 1460.", image: "", rating: 3.5, reviewCount: 30, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Whorlton Castle (Main)", lat: 54.418, lng: -1.238, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Castle with fine 14th-century gatehouse.", image: "", rating: 3.4, reviewCount: 22, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mulgrave Castle (Old Main)", lat: 54.478, lng: -0.698, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Dramatic castle ruin in woodland near Whitby.", image: "", rating: 3.5, reviewCount: 30, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Danby Castle (Main)", lat: 54.458, lng: -0.928, country: "England", type: "castle", era: "14th century", condition: "partial ruin", description: "Castle where Catherine Parr lived, partly a farmhouse.", image: "", rating: 3.4, reviewCount: 22, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Sheriff Hutton Castle (Main)", lat: 54.088, lng: -1.018, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Neville castle where Richard III's court was held.", image: "", rating: 3.5, reviewCount: 30, county: "Yorkshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Ravensworth Castle (Main)", lat: 54.478, lng: -1.658, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Impressive FitzHugh castle ruin near Richmond.", image: "", rating: 3.4, reviewCount: 22, county: "Yorkshire", tags: ["hidden-gem"], access: "restricted" },
  { name: "Snape Castle (Main)", lat: 54.268, lng: -1.608, country: "England", type: "castle", era: "15th century", condition: "partial ruin", description: "Castle where Catherine Parr grew up.", image: "", rating: 3.4, reviewCount: 22, county: "Yorkshire", tags: ["hidden-gem"], access: "restricted" },
  { name: "Crayke Castle (Main)", lat: 54.148, lng: -1.168, country: "England", type: "castle", era: "15th century", condition: "intact", description: "Bishop of Durham's castle, now private.", image: "", rating: 3.2, reviewCount: 14, county: "Yorkshire", tags: ["hidden-gem"], access: "restricted" },

  // Lancashire/Cheshire
  { name: "Peel Castle (Main)", lat: 54.228, lng: -4.698, country: "Isle of Man", type: "castle", era: "11th century", condition: "ruin", description: "Viking and medieval castle on St Patrick's Isle.", image: "", rating: 4.0, reviewCount: 130, county: "Isle of Man", tags: ["must-see"], access: "paid" },
  { name: "Hoghton Tower (Main)", lat: 53.728, lng: -2.558, country: "England", type: "fortified house", era: "16th century", condition: "intact", description: "Fortified hilltop house where James I knighted a loin of beef.", image: "", rating: 3.7, reviewCount: 55, county: "Lancashire", tags: ["hidden-gem"], access: "paid" },
  { name: "Clitheroe Castle (Main)", lat: 53.868, lng: -2.392, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle with one of the smallest keeps in England.", image: "", rating: 3.6, reviewCount: 42, county: "Lancashire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Greenhalgh Castle (Main)", lat: 53.838, lng: -2.852, country: "England", type: "castle", era: "15th century", condition: "ruin", description: "Last castle built in Lancashire, Royalist in the Civil War.", image: "", rating: 3.3, reviewCount: 18, county: "Lancashire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Peckforton Castle (Main)", lat: 53.108, lng: -2.698, country: "England", type: "castle", era: "19th century", condition: "restored", description: "Victorian mock-medieval castle, now a hotel.", image: "", rating: 3.8, reviewCount: 72, county: "Cheshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Beeston Castle (Main)", lat: 53.128, lng: -2.688, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Dramatic hilltop castle with views of eight counties.", image: "", rating: 4.0, reviewCount: 140, county: "Cheshire", tags: ["must-see"], access: "paid" },

  // Midlands extras
  { name: "Haddon Hall (Main)", lat: 53.188, lng: -1.628, country: "England", type: "fortified house", era: "12th century", condition: "intact", description: "One of the finest medieval manor houses in England.", image: "", rating: 4.2, reviewCount: 195, county: "Derbyshire", tags: ["must-see"], access: "paid" },
  { name: "Wingfield Manor (Main)", lat: 53.088, lng: -1.488, country: "England", type: "fortified house", era: "15th century", condition: "ruin", description: "Ralph Cromwell's manor where Mary Queen of Scots was imprisoned.", image: "", rating: 3.7, reviewCount: 55, county: "Derbyshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Codnor Castle (Main)", lat: 53.048, lng: -1.378, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Grey family castle ruin near Ripley.", image: "", rating: 3.3, reviewCount: 18, county: "Derbyshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mackworth Castle (Main)", lat: 52.928, lng: -1.528, country: "England", type: "castle", era: "15th century", condition: "ruin", description: "Castle gatehouse near Derby.", image: "", rating: 3.1, reviewCount: 10, county: "Derbyshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tutbury Castle (Main)", lat: 52.862, lng: -1.668, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Lancaster castle where Mary Queen of Scots was held.", image: "", rating: 3.8, reviewCount: 72, county: "Staffordshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Chartley Castle (Main)", lat: 52.838, lng: -1.908, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Ferrers castle ruin with cylindrical keep.", image: "", rating: 3.4, reviewCount: 22, county: "Staffordshire", tags: ["hidden-gem"], access: "restricted" },
  { name: "Eccleshall Castle (Main)", lat: 52.858, lng: -2.248, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Bishop of Lichfield's castle.", image: "", rating: 3.2, reviewCount: 14, county: "Staffordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tamworth Castle (Main)", lat: 52.635, lng: -1.692, country: "England", type: "castle", era: "11th century", condition: "restored", description: "Norman motte and bailey castle, now a museum.", image: "", rating: 3.8, reviewCount: 78, county: "Staffordshire", tags: ["must-see"], access: "paid" },
  { name: "Dudley Castle (Main)", lat: 52.528, lng: -2.088, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Castle ruin inside Dudley Zoo.", image: "", rating: 3.6, reviewCount: 42, county: "West Midlands", tags: ["hidden-gem"], access: "paid" },
  { name: "Maxstoke Castle (Main)", lat: 52.512, lng: -1.688, country: "England", type: "castle", era: "14th century", condition: "intact", description: "Moated castle, one of the best-preserved in England.", image: "", rating: 3.5, reviewCount: 28, county: "Warwickshire", tags: ["hidden-gem"], access: "restricted" },

  // East Anglia
  { name: "Castle Acre Castle (Main)", lat: 52.718, lng: 0.688, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Warenne castle with massive earthworks.", image: "", rating: 3.7, reviewCount: 55, county: "Norfolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Baconsthorpe Castle (Main)", lat: 52.898, lng: 1.148, country: "England", type: "fortified house", era: "15th century", condition: "ruin", description: "Heydon family moated fortified house.", image: "", rating: 3.5, reviewCount: 30, county: "Norfolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Caister Castle (Main)", lat: 52.648, lng: 1.728, country: "England", type: "castle", era: "15th century", condition: "ruin", description: "Fastolf castle with tall brick tower.", image: "", rating: 3.6, reviewCount: 42, county: "Norfolk", tags: ["hidden-gem"], access: "paid" },
  { name: "Weeting Castle (Main)", lat: 52.468, lng: 0.618, country: "England", type: "fortified house", era: "12th century", condition: "ruin", description: "Moated manor house ruin near Brandon.", image: "", rating: 3.3, reviewCount: 18, county: "Norfolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Bungay Castle (Main)", lat: 52.458, lng: 1.438, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Bigod castle with twin-towered gatehouse.", image: "", rating: 3.5, reviewCount: 30, county: "Suffolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Eye Castle (Main)", lat: 52.318, lng: 1.148, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Motte and bailey with Victorian folly atop.", image: "", rating: 3.3, reviewCount: 18, county: "Suffolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Clare Castle (Main)", lat: 52.078, lng: 0.588, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "De Clare motte and bailey in Clare Country Park.", image: "", rating: 3.4, reviewCount: 22, county: "Suffolk", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Leiston Abbey (Main)", lat: 52.208, lng: 1.568, country: "England", type: "abbey", era: "14th century", condition: "ruin", description: "Premonstratensian abbey near Sizewell.", image: "", rating: 3.5, reviewCount: 28, county: "Suffolk", tags: ["hidden-gem", "free"], access: "free" },

  // South/Southwest
  { name: "Lydford Castle (Main)", lat: 50.648, lng: -4.068, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Norman keep used as a stannary court prison.", image: "", rating: 3.4, reviewCount: 22, county: "Devon", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Totnes Castle (Main)", lat: 50.432, lng: -3.688, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Classic motte and shell keep overlooking Totnes.", image: "", rating: 3.6, reviewCount: 42, county: "Devon", tags: ["hidden-gem"], access: "paid" },
  { name: "Restormel Castle (Main)", lat: 50.448, lng: -4.668, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Perfectly circular shell keep above the Fowey.", image: "", rating: 3.8, reviewCount: 72, county: "Cornwall", tags: ["must-see"], access: "paid" },
  { name: "Launceston Castle (Main)", lat: 50.638, lng: -4.358, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Castle with unusual double keep on a high motte.", image: "", rating: 3.7, reviewCount: 55, county: "Cornwall", tags: ["hidden-gem"], access: "paid" },
  { name: "St Mawes Castle (Main)", lat: 50.158, lng: -5.018, country: "England", type: "castle", era: "16th century", condition: "intact", description: "Henry VIII cloverleaf-plan coastal fort.", image: "", rating: 3.8, reviewCount: 72, county: "Cornwall", tags: ["must-see"], access: "paid" },
  { name: "Old Sarum (Main)", lat: 51.098, lng: -1.808, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Iron Age hillfort, Norman castle and old cathedral site.", image: "", rating: 3.8, reviewCount: 78, county: "Wiltshire", tags: ["must-see"], access: "paid" },
  { name: "Sherborne Old Castle (Main)", lat: 50.948, lng: -2.508, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Roger of Salisbury's castle, slighted in the Civil War.", image: "", rating: 3.6, reviewCount: 42, county: "Dorset", tags: ["hidden-gem"], access: "paid" },
  { name: "Nunney Castle (Main)", lat: 51.228, lng: -2.378, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "French-style moated castle, slighted 1645.", image: "", rating: 3.7, reviewCount: 55, county: "Somerset", tags: ["hidden-gem", "free"], access: "free" },

  // Herefordshire/Gloucestershire
  { name: "Goodrich Castle (Main)", lat: 51.838, lng: -2.618, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "One of the finest medieval castles in the Wye Valley.", image: "", rating: 4.0, reviewCount: 135, county: "Herefordshire", tags: ["must-see"], access: "paid" },
  { name: "Wigmore Castle (Main)", lat: 52.318, lng: -2.918, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Mortimer stronghold on the Welsh Marches.", image: "", rating: 3.6, reviewCount: 42, county: "Herefordshire", tags: ["dramatic-ruin", "free"], access: "free" },
  { name: "Longtown Castle (Main)", lat: 51.948, lng: -2.968, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Castle with cylindrical keep near the Black Mountains.", image: "", rating: 3.5, reviewCount: 30, county: "Herefordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Clifford Castle", lat: 52.088, lng: -3.118, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Birthplace of Fair Rosamund, Marcher castle.", image: "", rating: 3.4, reviewCount: 22, county: "Herefordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Snodhill Castle", lat: 52.028, lng: -3.028, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Remote castle ruin in the Golden Valley.", image: "", rating: 3.4, reviewCount: 20, county: "Herefordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Ewyas Harold Castle", lat: 51.968, lng: -2.908, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Pre-Conquest castle motte near Pontrilas.", image: "", rating: 3.2, reviewCount: 14, county: "Herefordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "St Briavels Castle (Main)", lat: 51.748, lng: -2.648, country: "England", type: "castle", era: "12th century", condition: "intact", description: "Royal castle now a YHA hostel in the Forest of Dean.", image: "", rating: 3.6, reviewCount: 42, county: "Gloucestershire", tags: ["hidden-gem"], access: "paid" },
  { name: "Berkeley Castle (Main)", lat: 51.688, lng: -2.458, country: "England", type: "castle", era: "12th century", condition: "intact", description: "Castle where Edward II was murdered, still family-owned.", image: "", rating: 3.9, reviewCount: 95, county: "Gloucestershire", tags: ["must-see"], access: "paid" },
  { name: "Beverston Castle (Main)", lat: 51.658, lng: -2.218, country: "England", type: "castle", era: "13th century", condition: "partial ruin", description: "Berkeley castle with attached farmhouse.", image: "", rating: 3.3, reviewCount: 16, county: "Gloucestershire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Thornbury Castle (Main)", lat: 51.612, lng: -2.518, country: "England", type: "castle", era: "16th century", condition: "intact", description: "Stafford castle, now a luxury hotel.", image: "", rating: 3.8, reviewCount: 72, county: "Gloucestershire", tags: ["hidden-gem"], access: "paid" },

  // Northumberland extras
  { name: "Chillingham Castle (Main)", lat: 55.518, lng: -1.918, country: "England", type: "castle", era: "13th century", condition: "restored", description: "Said to be the most haunted castle in England.", image: "", rating: 3.9, reviewCount: 95, county: "Northumberland", tags: ["must-see"], access: "paid" },
  { name: "Aydon Castle (Main)", lat: 54.988, lng: -1.918, country: "England", type: "fortified house", era: "13th century", condition: "intact", description: "One of the finest fortified manor houses in England.", image: "", rating: 3.7, reviewCount: 55, county: "Northumberland", tags: ["hidden-gem"], access: "paid" },
  { name: "Belsay Castle (Main)", lat: 55.108, lng: -1.858, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Tower house with later hall and quarry garden.", image: "", rating: 3.8, reviewCount: 72, county: "Northumberland", tags: ["must-see"], access: "paid" },
  { name: "Langley Castle (Main)", lat: 54.908, lng: -2.278, country: "England", type: "tower house", era: "14th century", condition: "restored", description: "Restored tower house, now a hotel.", image: "", rating: 3.7, reviewCount: 55, county: "Northumberland", tags: ["hidden-gem"], access: "paid" },
  { name: "Chipchase Castle (Main)", lat: 55.078, lng: -2.148, country: "England", type: "castle", era: "14th century", condition: "intact", description: "Tower house with Jacobean manor, fine gardens.", image: "", rating: 3.5, reviewCount: 28, county: "Northumberland", tags: ["hidden-gem"], access: "paid" },
  { name: "Harbottle Castle (Main)", lat: 55.328, lng: -2.108, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Umfraville castle in Coquetdale.", image: "", rating: 3.3, reviewCount: 18, county: "Northumberland", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Mitford Castle (Main)", lat: 55.168, lng: -1.728, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Castle with unusual five-sided keep.", image: "", rating: 3.4, reviewCount: 22, county: "Northumberland", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Hepburn Bastle (Main)", lat: 55.408, lng: -1.878, country: "England", type: "bastle", era: "16th century", condition: "ruin", description: "Fortified farmhouse in the Cheviots.", image: "", rating: 3.2, reviewCount: 14, county: "Northumberland", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Elsdon Tower (Main)", lat: 55.238, lng: -2.098, country: "England", type: "tower house", era: "14th century", condition: "intact", description: "Vicar's pele tower in Elsdon village.", image: "", rating: 3.3, reviewCount: 18, county: "Northumberland", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Cresswell Tower (Main)", lat: 55.228, lng: -1.548, country: "England", type: "tower house", era: "14th century", condition: "restored", description: "Coastal tower house near Druridge Bay.", image: "", rating: 3.4, reviewCount: 22, county: "Northumberland", tags: ["hidden-gem", "free", "coastal"], access: "free" },

  // Cumbria extras
  { name: "Sizergh Castle (Main)", lat: 54.278, lng: -2.778, country: "England", type: "castle", era: "14th century", condition: "intact", description: "Strickland family pele tower with Elizabethan additions.", image: "", rating: 3.9, reviewCount: 92, county: "Cumbria", tags: ["must-see"], access: "paid" },
  { name: "Muncaster Castle (Main)", lat: 54.348, lng: -3.328, country: "England", type: "castle", era: "13th century", condition: "intact", description: "Pennington family castle with Himalayan gardens.", image: "", rating: 3.9, reviewCount: 88, county: "Cumbria", tags: ["must-see"], access: "paid" },
  { name: "Dacre Castle (Main)", lat: 54.658, lng: -2.818, country: "England", type: "tower house", era: "14th century", condition: "intact", description: "Dacre pele tower near Ullswater.", image: "", rating: 3.3, reviewCount: 18, county: "Cumbria", tags: ["hidden-gem"], access: "restricted" },
  { name: "Egremont Castle (Main)", lat: 54.478, lng: -3.528, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Castle with herringbone masonry on a mound.", image: "", rating: 3.4, reviewCount: 22, county: "Cumbria", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Cockermouth Castle (Main)", lat: 54.662, lng: -3.368, country: "England", type: "castle", era: "13th century", condition: "partial ruin", description: "Still partly occupied castle in Cockermouth.", image: "", rating: 3.5, reviewCount: 30, county: "Cumbria", tags: ["hidden-gem"], access: "restricted" },
  { name: "Piel Castle (Main)", lat: 54.062, lng: -3.168, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Castle on Piel Island, accessible by ferry.", image: "", rating: 3.7, reviewCount: 55, county: "Cumbria", tags: ["dramatic-ruin", "free", "coastal"], access: "free" },
  { name: "Arnside Tower (Main)", lat: 54.198, lng: -2.838, country: "England", type: "tower house", era: "15th century", condition: "ruin", description: "Pele tower ruin overlooking Morecambe Bay.", image: "", rating: 3.4, reviewCount: 22, county: "Cumbria", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Gleaston Castle (Main)", lat: 54.168, lng: -3.068, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Harrington castle ruin in Low Furness.", image: "", rating: 3.3, reviewCount: 18, county: "Cumbria", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Dalton Castle (Main)", lat: 54.148, lng: -3.178, country: "England", type: "tower house", era: "14th century", condition: "intact", description: "Pele tower now housing a museum.", image: "", rating: 3.4, reviewCount: 22, county: "Cumbria", tags: ["hidden-gem", "free"], access: "free" },

  // Southern England extras
  { name: "Scotney Castle (Main)", lat: 51.088, lng: 0.398, country: "England", type: "castle", era: "14th century", condition: "partial ruin", description: "Romantic moated castle in landscaped gardens.", image: "", rating: 4.2, reviewCount: 210, county: "Kent", tags: ["must-see"], access: "paid" },
  { name: "Sissinghurst Castle (Main)", lat: 51.118, lng: 0.578, country: "England", type: "castle", era: "16th century", condition: "partial ruin", description: "Famous for Vita Sackville-West's gardens.", image: "", rating: 4.3, reviewCount: 280, county: "Kent", tags: ["must-see"], access: "paid" },
  { name: "Saltwood Castle (Main)", lat: 51.088, lng: 1.078, country: "England", type: "castle", era: "12th century", condition: "intact", description: "Castle where the murder of Becket was plotted.", image: "", rating: 3.5, reviewCount: 28, county: "Kent", tags: ["hidden-gem"], access: "restricted" },
  { name: "Allington Castle (Main)", lat: 51.298, lng: 0.498, country: "England", type: "castle", era: "13th century", condition: "restored", description: "Moated castle near Maidstone.", image: "", rating: 3.4, reviewCount: 22, county: "Kent", tags: ["hidden-gem"], access: "restricted" },
  { name: "Herstmonceux Castle (Main)", lat: 50.868, lng: 0.328, country: "England", type: "castle", era: "15th century", condition: "restored", description: "Brick castle, once home to the Royal Observatory.", image: "", rating: 3.9, reviewCount: 95, county: "East Sussex", tags: ["must-see"], access: "paid" },
  { name: "Bramber Castle (Main)", lat: 50.888, lng: -0.312, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Norman castle ruin near Steyning.", image: "", rating: 3.4, reviewCount: 22, county: "West Sussex", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Amberley Castle (Main)", lat: 50.888, lng: -0.538, country: "England", type: "castle", era: "12th century", condition: "intact", description: "Bishop of Chichester's castle, now a hotel.", image: "", rating: 3.7, reviewCount: 52, county: "West Sussex", tags: ["hidden-gem"], access: "paid" },
  { name: "Portchester Castle (Main)", lat: 50.838, lng: -1.118, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Norman castle inside the best-preserved Roman fort in northern Europe.", image: "", rating: 4.0, reviewCount: 135, county: "Hampshire", tags: ["must-see"], access: "paid" },
  { name: "Bishop's Waltham Palace (Main)", lat: 51.008, lng: -1.208, country: "England", type: "palace", era: "12th century", condition: "ruin", description: "Bishop of Winchester's palace ruins.", image: "", rating: 3.5, reviewCount: 30, county: "Hampshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Wolvesey Castle (Main)", lat: 51.058, lng: -1.318, country: "England", type: "palace", era: "12th century", condition: "ruin", description: "Bishop of Winchester's medieval palace.", image: "", rating: 3.6, reviewCount: 42, county: "Hampshire", tags: ["hidden-gem", "free"], access: "free" },

  // Shropshire/Marches
  { name: "Stokesay Castle (Main)", lat: 52.398, lng: -2.818, country: "England", type: "fortified house", era: "13th century", condition: "intact", description: "Finest surviving fortified manor house in England.", image: "", rating: 4.2, reviewCount: 195, county: "Shropshire", tags: ["must-see"], access: "paid" },
  { name: "Ludlow Castle (Main)", lat: 52.368, lng: -2.718, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "Magnificent Marcher castle overlooking the Teme.", image: "", rating: 4.1, reviewCount: 175, county: "Shropshire", tags: ["must-see"], access: "paid" },
  { name: "Clun Castle (Main)", lat: 52.418, lng: -3.038, country: "England", type: "castle", era: "11th century", condition: "ruin", description: "FitzAlan castle on the River Clun.", image: "", rating: 3.5, reviewCount: 30, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Bishop's Castle (Main)", lat: 52.488, lng: -2.998, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Fragmentary castle remains in the town.", image: "", rating: 3.1, reviewCount: 10, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Hopton Castle (Main)", lat: 52.388, lng: -2.928, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Norman keep scene of a Civil War massacre.", image: "", rating: 3.5, reviewCount: 28, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Whittington Castle (Main)", lat: 52.878, lng: -2.998, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Moated castle linked to the Holy Grail legend.", image: "", rating: 3.6, reviewCount: 42, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Moreton Corbet Castle (Main)", lat: 52.798, lng: -2.708, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Medieval castle with Elizabethan wing.", image: "", rating: 3.5, reviewCount: 30, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Acton Burnell Castle (Main)", lat: 52.608, lng: -2.678, country: "England", type: "fortified house", era: "13th century", condition: "ruin", description: "Bishop of Bath's fortified manor, first English parliament site.", image: "", rating: 3.6, reviewCount: 42, county: "Shropshire", tags: ["hidden-gem", "free"], access: "free" },

  // Oxfordshire/Berkshire
  { name: "Minster Lovell Hall (Main)", lat: 51.798, lng: -1.528, country: "England", type: "fortified house", era: "15th century", condition: "ruin", description: "Lovell family manor house on the Windrush.", image: "", rating: 3.8, reviewCount: 72, county: "Oxfordshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Broughton Castle (Main)", lat: 52.038, lng: -1.398, country: "England", type: "castle", era: "14th century", condition: "intact", description: "Moated castle, Parliamentarian headquarters in the Civil War.", image: "", rating: 3.8, reviewCount: 68, county: "Oxfordshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Donnington Castle (Main)", lat: 51.428, lng: -1.338, country: "England", type: "castle", era: "14th century", condition: "ruin", description: "Twin-towered gatehouse, sole survivor of Civil War siege.", image: "", rating: 3.6, reviewCount: 42, county: "Berkshire", tags: ["hidden-gem", "free"], access: "free" },

  // Durham extras
  { name: "Barnard Castle (Main)", lat: 54.542, lng: -1.918, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Baliol castle on the Tees.", image: "", rating: 3.7, reviewCount: 55, county: "County Durham", tags: ["hidden-gem"], access: "paid" },
  { name: "Raby Castle (Main)", lat: 54.618, lng: -1.848, country: "England", type: "castle", era: "14th century", condition: "intact", description: "One of the finest medieval castles in England.", image: "", rating: 4.0, reviewCount: 140, county: "County Durham", tags: ["must-see"], access: "paid" },
  { name: "Bowes Castle (Main)", lat: 54.518, lng: -2.018, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Norman keep on Roman fort at Stainmore Pass.", image: "", rating: 3.4, reviewCount: 22, county: "County Durham", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Brancepeth Castle (Main)", lat: 54.718, lng: -1.688, country: "England", type: "castle", era: "12th century", condition: "intact", description: "Neville castle, now private.", image: "", rating: 3.3, reviewCount: 18, county: "County Durham", tags: ["hidden-gem"], access: "restricted" },
  { name: "Witton Castle (Main)", lat: 54.648, lng: -1.778, country: "England", type: "castle", era: "15th century", condition: "intact", description: "Castle now part of a holiday park.", image: "", rating: 3.2, reviewCount: 14, county: "County Durham", tags: ["hidden-gem"], access: "paid" },

  // Nottinghamshire/Lincolnshire
  { name: "Newark Castle (Main)", lat: 53.078, lng: -0.808, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Castle where King John died in 1216.", image: "", rating: 3.7, reviewCount: 55, county: "Nottinghamshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Rufford Abbey (Main)", lat: 53.208, lng: -1.078, country: "England", type: "abbey", era: "12th century", condition: "ruin", description: "Cistercian abbey ruins in Rufford Country Park.", image: "", rating: 3.5, reviewCount: 30, county: "Nottinghamshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Bolingbroke Castle (Main)", lat: 53.158, lng: 0.048, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Birthplace of Henry IV, hexagonal castle.", image: "", rating: 3.6, reviewCount: 40, county: "Lincolnshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Tattershall Castle (Main)", lat: 53.098, lng: -0.208, country: "England", type: "castle", era: "15th century", condition: "restored", description: "Great brick tower keep, finest in England.", image: "", rating: 4.0, reviewCount: 140, county: "Lincolnshire", tags: ["must-see"], access: "paid" },
  { name: "Somerton Castle (Main)", lat: 53.168, lng: -0.508, country: "England", type: "castle", era: "13th century", condition: "ruin", description: "Bishop of Lincoln's castle where King John of France was held.", image: "", rating: 3.3, reviewCount: 16, county: "Lincolnshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "South Kyme Tower (Main)", lat: 53.028, lng: -0.268, country: "England", type: "tower house", era: "14th century", condition: "ruin", description: "Sole surviving tower of a larger castle.", image: "", rating: 3.2, reviewCount: 12, county: "Lincolnshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Hussey Tower (Main)", lat: 52.978, lng: -0.028, country: "England", type: "tower house", era: "15th century", condition: "ruin", description: "Brick tower in Boston town.", image: "", rating: 3.2, reviewCount: 14, county: "Lincolnshire", tags: ["hidden-gem", "free"], access: "free" },

  // Leicestershire/Northamptonshire
  { name: "Ashby de la Zouch Castle (Main)", lat: 52.748, lng: -1.478, country: "England", type: "castle", era: "15th century", condition: "ruin", description: "Hastings castle with Ivanhoe connections.", image: "", rating: 3.8, reviewCount: 72, county: "Leicestershire", tags: ["must-see"], access: "paid" },
  { name: "Kirby Muxloe Castle (Main)", lat: 52.638, lng: -1.258, country: "England", type: "castle", era: "15th century", condition: "ruin", description: "Unfinished brick castle of William Hastings.", image: "", rating: 3.6, reviewCount: 42, county: "Leicestershire", tags: ["hidden-gem"], access: "paid" },
  { name: "Rockingham Castle (Main)", lat: 52.498, lng: -0.818, country: "England", type: "castle", era: "11th century", condition: "intact", description: "Royal castle, Dickens' model for Chesney Wold.", image: "", rating: 3.8, reviewCount: 72, county: "Northamptonshire", tags: ["hidden-gem"], access: "paid" },
  { name: "Fotheringhay Castle (Main)", lat: 52.528, lng: -0.428, country: "England", type: "castle", era: "12th century", condition: "ruin", description: "Where Mary Queen of Scots was executed, now just a mound.", image: "", rating: 3.5, reviewCount: 30, county: "Northamptonshire", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Kirby Hall (Main)", lat: 52.498, lng: -0.618, country: "England", type: "country house", era: "16th century", condition: "ruin", description: "Elizabethan mansion with fine gardens.", image: "", rating: 3.8, reviewCount: 68, county: "Northamptonshire", tags: ["hidden-gem"], access: "paid" },

  // More Ireland - Wicklow/Carlow/Kildare
  { name: "Kindlestown Castle (Main)", lat: 53.128, lng: -6.108, country: "Ireland", type: "tower house", era: "15th century", condition: "ruin", description: "Tower house overlooking Greystones.", image: "", rating: 3.3, reviewCount: 18, county: "County Wicklow", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Black Castle (Wicklow Main)", lat: 52.978, lng: -6.048, country: "Ireland", type: "castle", era: "12th century", condition: "ruin", description: "FitzWilliam castle on the coast at Wicklow town.", image: "", rating: 3.5, reviewCount: 30, county: "County Wicklow", tags: ["hidden-gem", "free", "coastal"], access: "free" },
  { name: "Powerscourt Castle", lat: 53.188, lng: -6.188, country: "Ireland", type: "country house", era: "18th century", condition: "restored", description: "Palladian mansion with famous gardens.", image: "", rating: 4.3, reviewCount: 280, county: "County Wicklow", tags: ["must-see"], access: "paid" },
  { name: "Russborough House", lat: 53.118, lng: -6.538, country: "Ireland", type: "country house", era: "18th century", condition: "intact", description: "Palladian house with Beit art collection.", image: "", rating: 4.0, reviewCount: 130, county: "County Wicklow", tags: ["must-see"], access: "paid" },
  { name: "Ballyloughan Castle (Main)", lat: 52.788, lng: -6.878, country: "Ireland", type: "castle", era: "13th century", condition: "ruin", description: "Anglo-Norman hall-keep castle near Bagenalstown.", image: "", rating: 3.4, reviewCount: 22, county: "County Carlow", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Carlow Castle (Main)", lat: 52.838, lng: -6.928, country: "Ireland", type: "castle", era: "13th century", condition: "ruin", description: "Half-demolished Norman keep in Carlow town.", image: "", rating: 3.5, reviewCount: 32, county: "County Carlow", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Kilkea Castle (Main)", lat: 52.948, lng: -6.948, country: "Ireland", type: "castle", era: "12th century", condition: "restored", description: "One of the oldest inhabited castles in Ireland, now a hotel.", image: "", rating: 3.7, reviewCount: 55, county: "County Kildare", tags: ["hidden-gem"], access: "paid" },
  { name: "Maynooth Castle (Main)", lat: 53.378, lng: -6.588, country: "Ireland", type: "castle", era: "12th century", condition: "ruin", description: "FitzGerald castle keep near Maynooth University.", image: "", rating: 3.6, reviewCount: 42, county: "County Kildare", tags: ["hidden-gem", "free"], access: "free" },

  // More Scotland - Stirling/Lothian
  { name: "Doune Castle (Main)", lat: 56.188, lng: -4.058, country: "Scotland", type: "castle", era: "14th century", condition: "intact", description: "Famous as Monty Python's Castle and Winterfell location.", image: "", rating: 4.2, reviewCount: 220, county: "Stirlingshire", tags: ["must-see"], access: "paid" },
  { name: "Castle Campbell (Main)", lat: 56.148, lng: -3.678, country: "Scotland", type: "castle", era: "15th century", condition: "ruin", description: "Campbell stronghold in Dollar Glen.", image: "", rating: 3.9, reviewCount: 92, county: "Clackmannanshire", tags: ["must-see"], access: "paid" },
  { name: "Blackness Castle (Main)", lat: 56.008, lng: -3.518, country: "Scotland", type: "castle", era: "15th century", condition: "intact", description: "Ship-shaped castle on the Forth, used in Outlander.", image: "", rating: 4.0, reviewCount: 145, county: "West Lothian", tags: ["must-see"], access: "paid" },
  { name: "Linlithgow Palace (Main)", lat: 55.978, lng: -3.598, country: "Scotland", type: "palace", era: "15th century", condition: "ruin", description: "Birthplace of Mary Queen of Scots.", image: "", rating: 4.1, reviewCount: 175, county: "West Lothian", tags: ["must-see"], access: "paid" },
  { name: "Craigmillar Castle (Main)", lat: 55.928, lng: -3.148, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Tower house with remarkable courtyard defences.", image: "", rating: 4.0, reviewCount: 140, county: "Edinburgh", tags: ["must-see"], access: "paid" },
  { name: "Dirleton Castle (Main)", lat: 56.058, lng: -2.778, country: "Scotland", type: "castle", era: "13th century", condition: "ruin", description: "De Vaux castle with beautiful gardens.", image: "", rating: 3.9, reviewCount: 95, county: "East Lothian", tags: ["must-see"], access: "paid" },
  { name: "Tantallon Castle (Main)", lat: 56.058, lng: -2.648, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Douglas fortress with massive curtain wall facing the sea.", image: "", rating: 4.1, reviewCount: 170, county: "East Lothian", tags: ["must-see"], access: "paid" },
  { name: "Hailes Castle (Main)", lat: 55.948, lng: -2.558, country: "Scotland", type: "castle", era: "13th century", condition: "ruin", description: "Hepburn castle on the Tyne.", image: "", rating: 3.6, reviewCount: 40, county: "East Lothian", tags: ["hidden-gem", "free"], access: "free" },
  { name: "Crichton Castle (Main)", lat: 55.838, lng: -2.988, country: "Scotland", type: "castle", era: "14th century", condition: "ruin", description: "Castle with remarkable Italianate diamond-faceted facade.", image: "", rating: 3.8, reviewCount: 68, county: "Midlothian", tags: ["hidden-gem"], access: "paid" },
  { name: "Borthwick Castle (Main)", lat: 55.828, lng: -3.068, country: "Scotland", type: "castle", era: "15th century", condition: "intact", description: "Massive twin-towered keep, tallest in Scotland.", image: "", rating: 3.7, reviewCount: 55, county: "Midlothian", tags: ["hidden-gem"], access: "paid" },
  { name: "Roslin Castle (Main)", lat: 55.858, lng: -3.168, country: "Scotland", type: "castle", era: "14th century", condition: "partial ruin", description: "Sinclair castle near Rosslyn Chapel.", image: "", rating: 3.5, reviewCount: 30, county: "Midlothian", tags: ["hidden-gem", "free"], access: "free" },
];
