$sitePath = "C:\Users\Clawzisabot\.openclaw\workspace\castles\site"

# Define enrichment data for all 25 castles
$castles = @{

"windsor-castle" = @{
  narrativeQuote = '"In 1992, a fire that started in Queen Victoria''s Private Chapel tore through Windsor Castle for fifteen hours, destroying or damaging 115 rooms. The five-year restoration cost £36.5 million — funded by opening Buckingham Palace to tourists for the first time."'
  about1 = '<p class="drop-cap">There is a particular quality to the light at Windsor — the way it falls through the Upper Ward in late afternoon, catching the pale Portland stone and turning the Round Tower gold. <span class="highlight">This is the oldest continuously occupied castle in the world</span>, a place where nearly a thousand years of monarchy have left their mark in every corridor and courtyard.</p>'
  about2 = '<p>William the Conqueror chose this chalk bluff above the Thames in 1070, positioning his fortress a day''s march from the Tower of London. Every monarch since Henry I has lived here. <span class="highlight">Edward III was born within these walls and spent £51,000 rebuilding them</span> — the most expensive secular building project of medieval England. Henry VIII added the great gatehouse. Charles II tried to rival Versailles. George IV spent a staggering £300,000 on the State Apartments, creating what art historians call the finest expression of Georgian taste in existence.</p>'
  about3 = '<p>Today, Windsor is very much a working palace — the King''s standard flies when he''s in residence, and you might catch the Changing of the Guard in the Lower Ward. <span class="highlight">St George''s Chapel alone is worth the visit</span>: a masterpiece of Perpendicular Gothic where ten monarchs are buried, including Henry VIII and Charles I. The Semi-State Rooms, opened only in winter, are among the most lavishly decorated interiors in Britain.</p>'
  photoBreakQuote = '"A thousand years of power, prayer, and reinvention — written in stone above the Thames."'
}

"edinburgh-castle" = @{
  narrativeQuote = '"In 1314, just thirty men led by Thomas Randolph scaled the castle''s sheer north face in darkness, using a secret path known to only one soldier who''d used it to visit his girlfriend in town. They recaptured Scotland''s most important fortress without a single alarm being raised."'
  about1 = '<p class="drop-cap">It rises from the city like a geological fact — <span class="highlight">an extinct volcano crowned with battlements</span>, visible from nearly every street in Edinburgh. Castle Rock has been fortified since the Iron Age, and standing on its ramparts feels less like visiting a building than occupying a force of nature.</p>'
  about2 = '<p>This is the <span class="highlight">most besieged place in Britain</span>, with twenty-six recorded sieges across eleven centuries. The Honours of Scotland — crown, sceptre, and sword of state — were hidden here from Cromwell, bricked behind a wall and forgotten until Walter Scott rediscovered them in 1818. The Stone of Destiny, upon which Scottish kings were crowned, returned here in 1996 after seven centuries in English hands. Mons Meg, the massive medieval siege cannon, still sits on the battlements where it''s rested since the 15th century.</p>'
  about3 = '<p>The One O''Clock Gun fires daily (except Sundays) from the Half Moon Battery — a tradition since 1861. <span class="highlight">St Margaret''s Chapel, built around 1130, is the oldest surviving building in Edinburgh.</span> The castle draws over two million visitors a year, and the Royal Edinburgh Military Tattoo transforms the esplanade each August into one of the world''s great performance spaces.</p>'
  photoBreakQuote = '"Twenty-six sieges. A thousand years of defiance. The rock endures."'
}

"hampton-court-palace" = @{
  narrativeQuote = '"In 1528, Cardinal Wolsey — the most powerful man in England after the King — gifted his magnificent palace to Henry VIII in a desperate bid to save his own neck. It didn''t work. Wolsey was dead within two years, and Henry had already begun expanding the kitchens to feed a court of 1,200."'
  about1 = '<p class="drop-cap">Two palaces occupy the same ground here, and the contrast is the whole story. <span class="highlight">Walk through the Tudor gatehouse with its terracotta roundels, and you enter Henry VIII''s world</span> — vast kitchens, a soaring Great Hall with a hammerbeam roof, and the haunted gallery where Catherine Howard''s ghost is said to scream.</p>'
  about2 = '<p>Wolsey built Hampton Court as the grandest private residence in England, with over 280 guest rooms. When Henry VIII took it, he made it grander still — adding the Great Hall, the Chapel Royal, and kitchens that could roast whole oxen. <span class="highlight">A century and a half later, William III hired Christopher Wren to demolish it all and build a rival to Versailles.</span> Wren got halfway before William died, leaving the palace frozen between two architectural worlds: Tudor brick and Baroque Portland stone.</p>'
  about3 = '<p>The palace gardens are spectacular in their own right — the Great Vine, planted in 1768, is the oldest and largest grape vine in the world, still producing hundreds of pounds of grapes each year. <span class="highlight">The famous Maze has been bewildering visitors since the 1690s.</span> The real tennis court, built for Henry VIII, is one of the oldest in the world and still in use.</p>'
  photoBreakQuote = '"Two kings, two centuries, two palaces — sharing a single heartbeat of Tudor brick and Baroque stone."'
}

"warwick-castle" = @{
  narrativeQuote = '"In 1449, Richard Neville — ''the Kingmaker'' — inherited Warwick Castle and used it as a base to depose not one but two kings during the Wars of the Roses. He put Edward IV on the throne, then switched sides and briefly restored Henry VI, making him the most powerful subject in English history."'
  about1 = '<p class="drop-cap">Warwick Castle does not creep up on you. It announces itself — <span class="highlight">a curtain wall of pale sandstone rising sheer from the banks of the River Avon</span>, towers punching skyward, the whole composition so perfectly medieval it seems staged. It is, in fact, one of the finest examples of 14th-century military architecture in Europe.</p>'
  about2 = '<p>William the Conqueror raised the first fortification here in 1068, just two years after Hastings. <span class="highlight">The castle passed through the hands of England''s most powerful families</span> — the Beauchamps, the Nevilles, the Dudleys — each leaving their mark in stone and blood. The Beauchamp earls built Caesar''s Tower and Guy''s Tower in the 14th century, their walls up to 10 feet thick. In 1605, the castle was granted to Sir Fulke Greville, who spent £20,000 converting the medieval fortress into a comfortable country house.</p>'
  about3 = '<p>Now operated by Merlin Entertainments, Warwick Castle is one of Britain''s most-visited heritage attractions. <span class="highlight">The Great Hall contains a genuine suit of armour worn at the Battle of Agincourt.</span> The castle grounds include a working trebuchet — the largest in the world — which fires daily in summer. The Peacock Garden and the Victorian Rose Garden offer a gentler counterpoint to the military architecture above.</p>'
  photoBreakQuote = '"The Kingmaker''s fortress, where the Wars of the Roses were plotted over dinner."'
}

"blenheim-palace" = @{
  narrativeQuote = '"On 30 November 1874, during a house party at Blenheim, Lady Randolph Churchill went into premature labour and gave birth in a ground-floor cloakroom. The baby — Winston Leonard Spencer Churchill — would grow up to save the free world."'
  about1 = '<p class="drop-cap">Blenheim is not a house. It is a <span class="highlight">nation''s thank-you letter, written in stone</span>. The scale is deliberately overwhelming — Vanbrugh and Hawksmoor designed it as a monument first and a residence second, and approaching it across the Great Court you understand immediately that this is architecture as national statement.</p>'
  about2 = '<p>Queen Anne gifted the royal manor of Woodstock to John Churchill, 1st Duke of Marlborough, after his crushing victory over the French at the Battle of Blenheim in 1704. <span class="highlight">The palace took seventeen years to build and nearly bankrupted the nation</span> — Parliament voted £240,000, but costs spiralled so badly that the Duchess had to fund completion herself. Capability Brown later transformed 2,000 acres of formal gardens into the quintessential English landscape, damming a stream to create the lake that perfectly mirrors Vanbrugh''s Grand Bridge.</p>'
  about3 = '<p>The palace remains home to the Dukes of Marlborough — it is the only non-royal, non-episcopal country house in England to hold the title of ''palace.'' <span class="highlight">The room where Churchill was born is preserved as a permanent exhibition.</span> The Long Library, at 180 feet, is the longest room in any English house. The formal gardens include the Pleasure Gardens, a butterfly house, and a hedge maze.</p>'
  photoBreakQuote = '"A grateful nation''s monument — where triumph and extravagance share equal footing."'
}

"chatsworth-house" = @{
  narrativeQuote = '"In 1569, Mary, Queen of Scots was imprisoned at Chatsworth under the watch of Bess of Hardwick — a woman so formidable she''d outlive four husbands and become the second-richest woman in Elizabethan England after the Queen herself."'
  about1 = '<p class="drop-cap">The first glimpse stops you cold: a golden palace materialising across the Derwent, backed by moorland that stretches to the sky. <span class="highlight">They call it the ''Palace of the Peak''</span>, and the title is earned. Chatsworth doesn''t belong to the landscape — it commands it.</p>'
  about2 = '<p>Bess of Hardwick and her husband William Cavendish built the original Elizabethan house in the 1550s. The 1st Duke demolished it a century later and raised the present Baroque palace, whose Painted Hall — with ceilings by Louis Laguerre — still takes the breath away. <span class="highlight">The 6th Duke, known as the ''Bachelor Duke'', transformed Chatsworth into a treasure house</span>, commissioning Joseph Paxton to build the Great Conservatory, a glass cathedral that inspired the Crystal Palace. The art collection spans Rembrandt, Veronese, and Lucian Freud.</p>'
  about3 = '<p>Chatsworth today feels genuinely lived-in — the Cavendish family still occupies the private wing. The 105-acre garden is a masterpiece in itself: <span class="highlight">the Emperor Fountain shoots water 290 feet into the air</span>, powered entirely by gravity from lakes on the moor above. The Farmyard and Adventure Playground make it one of the best family days out in England.</p>'
  photoBreakQuote = '"Where Bess of Hardwick imprisoned a queen and built a dynasty that endures five centuries later."'
}

"canterbury-cathedral" = @{
  narrativeQuote = '"On 29 December 1170, four knights burst into Canterbury Cathedral and murdered Archbishop Thomas Becket on the steps of the altar. Within three years, miracles were reported at his tomb, pilgrims flooded in, and Canterbury became the most important pilgrimage site in medieval England."'
  about1 = '<p class="drop-cap">You hear Canterbury before you see it — the bells carry across the Kentish fields, calling out from a tower that has anchored English Christianity for fourteen centuries. <span class="highlight">This is the mother church of the worldwide Anglican Communion</span>, and stepping through the Christ Church Gate feels like crossing a threshold between the modern city and the medieval world.</p>'
  about2 = '<p>Augustine arrived here in 597 AD, sent by Pope Gregory the Great to convert the Anglo-Saxons. The cathedral has been rebuilt multiple times — by the Normans after a fire in 1067, and spectacularly after another fire in 1174, when <span class="highlight">William of Sens designed the revolutionary Gothic choir that would influence English architecture for centuries</span>. But it was Becket''s murder that made Canterbury. Geoffrey Chaucer''s pilgrims were heading here; the stained glass windows telling Becket''s story are among the finest medieval glass in the world.</p>'
  about3 = '<p>The cathedral precinct is a world unto itself — cloisters, the Chapter House, and the atmospheric ruins of the monastery. <span class="highlight">The medieval water system, with its ingenious plumbing, is one of the most remarkable surviving examples in Europe.</span> Evensong, sung daily by the cathedral choir, remains the most atmospheric way to experience a building that has shaped the spiritual life of a nation.</p>'
  photoBreakQuote = '"Where Becket fell, a nation knelt — and pilgrims have walked these stones for eight hundred years."'
}

"bamburgh-castle" = @{
  narrativeQuote = '"In 1464, Bamburgh became the first castle in England to be damaged by gunpowder artillery, when the Yorkist Earl of Warwick turned his cannons on its walls during the Wars of the Roses. The bombardment was so savage it punched holes through masonry that had stood since the Normans."'
  about1 = '<p class="drop-cap">There are castles, and then there is Bamburgh — <span class="highlight">a fortress so vast it seems to grow from the volcanic rock itself</span>, its walls dropping sheer to the beach on one side and commanding views to Holy Island and the Farne Islands on the other. This is the ancient seat of the kings of Northumbria, and it looks every inch the part.</p>'
  about2 = '<p>The Anglo-Saxon kings made Bamburgh their capital in the 6th century, and the site has been fortified for over 1,400 years. <span class="highlight">It was here that the legendary King Ida founded the kingdom of Bernicia in 547 AD.</span> The Normans built the great keep that still dominates the skyline, and Henry II rebuilt much of the castle in the 12th century. After centuries of decay, the Victorian industrialist Lord Armstrong purchased and restored it in the 1890s, installing what was then cutting-edge hydraulic technology — including a hydraulic lift and one of the earliest domestic hydroelectric power systems.</p>'
  about3 = '<p>Today, Bamburgh is still home to the Armstrong family and feels more like a stately home than a ruin. <span class="highlight">The King''s Hall houses one of the finest collections of arms and armour in the North of England.</span> The beach below — regularly voted one of Britain''s best — stretches for miles in both directions. On a clear day, you can see the outline of Lindisfarne rising from the sea.</p>'
  photoBreakQuote = '"The Anglo-Saxon kings chose this rock for a reason. Fourteen centuries later, you can still feel why."'
}

"fountains-abbey" = @{
  narrativeQuote = '"In 1132, thirteen Benedictine monks, expelled from St Mary''s Abbey in York for wanting to follow a stricter rule, walked barefoot into the frozen Skell Valley with nothing but a crucifix. Within a century, their Cistercian monastery had become one of the wealthiest in England."'
  about1 = '<p class="drop-cap">You descend through woodland and suddenly there it is: <span class="highlight">the roofless nave soaring open to the Yorkshire sky</span>, pillars marching in perfect rhythm, the River Skell threading quietly through ruins that seem to have grown from the valley floor. Fountains Abbey is arguably the most beautiful ruin in England.</p>'
  about2 = '<p>Those thirteen expelled monks chose this ''place remote from all the world'' deliberately — the Cistercian ideal demanded poverty, manual labour, and isolation from secular life. <span class="highlight">Within 200 years, Fountains had become spectacularly wealthy</span>, owning vast sheep farms across Yorkshire and producing prodigious quantities of wool and lead. The great tower, added by Abbot Marmaduke Huby around 1500, was a statement of confidence. Thirty-nine years later, Henry VIII dissolved it all. The lead was stripped from the roof, the bells melted down, and the monks scattered.</p>'
  about3 = '<p>In the 18th century, the ruins were incorporated into John Aislabie''s extraordinary Studley Royal Water Garden — <span class="highlight">a masterpiece of Georgian landscape design with moon ponds, a Temple of Piety, and geometric canals</span>. Together, the abbey and garden form a UNESCO World Heritage Site. The deer park surrounding it is home to some 500 red, fallow, and sika deer.</p>'
  photoBreakQuote = '"Thirteen monks, one frozen valley, and eight centuries of silence since the last prayer was spoken here."'
}

"stirling-castle" = @{
  narrativeQuote = '"In 1543, nine-month-old Mary was crowned Queen of Scots in the Chapel Royal at Stirling. She screamed through the entire ceremony. Thirty years later, her infant son James VI was baptised in the same chapel with a three-day festival that included the first recorded fireworks display in Scotland."'
  about1 = '<p class="drop-cap">Stirling Castle sits on a volcanic crag where the Highlands meet the Lowlands, <span class="highlight">commanding the lowest bridging point of the River Forth</span>. Whoever held Stirling held Scotland — and everyone from William Wallace to Bonnie Prince Charlie understood this. The castle feels less like a medieval fortress than a hinge upon which history turns.</p>'
  about2 = '<p>Eight sieges were fought here during the Wars of Scottish Independence alone. Robert the Bruce captured the castle in 1314 after his victory at Bannockburn, fought within sight of these walls. <span class="highlight">The Renaissance Palace, built by James V in the 1540s, is the finest example of Renaissance architecture in Scotland</span>, its exterior carved with wild figures and grotesques. The Great Hall, completed by James IV in 1503, was the largest medieval banqueting hall ever built in Scotland, its hammerbeam roof recently restored to its original golden splendour.</p>'
  about3 = '<p>The castle has undergone a remarkable restoration programme. <span class="highlight">The Stirling Heads — a series of carved oak roundels depicting kings, queens, and courtiers — have been painstakingly recreated</span> and now hang again in the King''s Inner Hall. The Regimental Museum of the Argyll and Sutherland Highlanders adds a military dimension, while the views from the ramparts — stretching from the Ochils to the Trossachs — are among the finest in Scotland.</p>'
  photoBreakQuote = '"Scotland''s kings were crowned here, Scotland''s battles were fought for here. The rock remembers all of it."'
}

"durham-cathedral" = @{
  narrativeQuote = '"In 875 AD, monks fled Lindisfarne carrying the body of St Cuthbert to save it from Viking raiders. For seven years they wandered northern England with their sacred burden, until — according to legend — the saint''s coffin became immovable at a hill above the River Wear. They built a church on that spot. It became Durham."'
  about1 = '<p class="drop-cap">Durham Cathedral does not reveal itself gradually. You turn a corner on the peninsula and it is simply <span class="highlight">there — massive, ancient, absolute</span>, its twin towers and central tower rising from a wooded gorge above the River Wear. UNESCO calls it ''the largest and most perfect example of Norman architecture in England.'' They are underselling it.</p>'
  about2 = '<p>Construction began in 1093, and the cathedral was substantially complete within forty years — an astonishing feat. <span class="highlight">Its ribbed vault, the first of its kind in Europe, was a structural revolution</span> that would transform Gothic architecture across the continent. The carved pillars, incised with bold geometric zigzags, spirals, and fluting, are unmistakably Norman in their massive confidence. St Cuthbert''s shrine lies behind the high altar, while the Venerable Bede — the father of English history — is entombed in the Galilee Chapel at the west end.</p>'
  about3 = '<p>The Cloisters, shared with the castle next door (together a UNESCO World Heritage Site), are atmospheric at any time of year. <span class="highlight">The cathedral doubled as Hogwarts in the first two Harry Potter films</span> — the Chapter House cloister is instantly recognisable. The tower climb (325 steps) rewards you with panoramic views over the medieval city. Evensong, sung daily by the cathedral choir, echoes through a space that has heard prayer without interruption for nearly a millennium.</p>'
  photoBreakQuote = '"The monks carried their saint for seven years. They chose this rock above the river, and it has not moved since."'
}

"dover-castle" = @{
  narrativeQuote = '"In May 1940, deep in the tunnels beneath Dover Castle, Vice-Admiral Bertram Ramsay coordinated Operation Dynamo from a cramped, chalk-walled room — directing the evacuation of 338,226 Allied soldiers from the beaches of Dunkirk in nine days. The tunnels had been dug during the Napoleonic Wars to house troops; they saved an army."'
  about1 = '<p class="drop-cap">Standing on the white cliffs with France visible on a clear day, Dover Castle is <span class="highlight">the most strategically important fortress in English history</span>. It has been called the ''Key to England'' since at least the 12th century, and for good reason — whoever controls these cliffs controls the shortest crossing between Britain and the continent.</p>'
  about2 = '<p>The Romans built a lighthouse here — the <span class="highlight">Pharos, still standing at nearly 2,000 years old, is one of the tallest Roman structures in Britain</span>. Next to it stands the Saxon church of St Mary in Castro. Henry II built the massive Great Tower in the 1180s, a palace-fortress designed to impress visiting dignitaries arriving from France. The medieval tunnels were expanded during the Napoleonic Wars to house over 2,000 troops, and then again in World War II when they became the nerve centre for Operation Dynamo.</p>'
  about3 = '<p>The wartime tunnels are the highlight for many visitors — the atmospheric re-creation of the Dynamo planning rooms brings the 1940 evacuation to vivid life. <span class="highlight">The Great Tower has been refurnished as it would have appeared in Henry II''s time</span>, with richly painted walls and replica furnishings that give a startling sense of medieval colour. The secret wartime hospital, deep underground, is genuinely chilling.</p>'
  photoBreakQuote = '"The Key to England — where Roman lighthouses and wartime tunnels share the same chalk cliffs."'
}

"caernarfon-castle" = @{
  narrativeQuote = '"Edward I deliberately modelled Caernarfon''s polygonal towers and banded masonry on the walls of Constantinople — a calculated message to the conquered Welsh that his power was imperial, descended from Rome itself. The castle was never finished, but the message was received."'
  about1 = '<p class="drop-cap">Caernarfon Castle does not invite you in. It confronts you — <span class="highlight">a wall of angular towers and banded stonework rising from the banks of the River Seiont</span>, its Eagle Tower still bearing the stone eagle that proclaimed Edward I''s imperial ambitions. This was designed to be the mightiest castle in Wales, and it succeeds.</p>'
  about2 = '<p>Edward I began building Caernarfon in 1283, deliberately choosing the site of a former Norman motte and Roman fort (Segontium). <span class="highlight">The castle cost approximately £27,000 to build — the equivalent of many billions today</span> — more than any other castle in the ''Iron Ring'' that Edward threw around North Wales. Master James of St George, the greatest military architect of his age, designed the defences. In 1294, the Welsh under Madog ap Llywelyn attacked and nearly captured the still-incomplete castle, prompting Edward to pour even more resources into its construction.</p>'
  about3 = '<p>In 1969, Prince Charles was invested as Prince of Wales in a ceremony at Caernarfon, designed by Lord Snowdon. <span class="highlight">The castle is part of the UNESCO World Heritage Site ''Castles and Town Walls of King Edward in Gwynedd''</span>, along with Conwy, Harlech, and Beaumaris. The Eagle Tower houses an exhibition on the Princes of Wales, and the Queen''s Tower contains the Royal Welsh Fusiliers Museum. The town walls, largely intact, are among the finest medieval town defences in Europe.</p>'
  photoBreakQuote = '"Edward built this castle to look like Constantinople. He wanted the Welsh to understand: resistance was futile."'
}

"tower-of-london" = @{
  narrativeQuote = '"In 1671, Colonel Thomas Blood disguised himself as a clergyman, befriended the elderly Keeper of the Jewels, and attempted to steal the Crown Jewels. He flattened the crown with a mallet to fit it in his coat and filed the sceptre in half — but was caught at the gates. Charles II was so amused he pardoned Blood and gave him a pension."'
  about1 = '<p class="drop-cap">The Tower squats at the edge of the Thames like something that has always been there, <span class="highlight">more a fact of London than a building in it</span>. William the Conqueror began the White Tower in 1066 to terrify the conquered Saxons, and nearly a millennium later, it still carries that energy — ancient, imposing, and faintly menacing.</p>'
  about2 = '<p>This single fortress has served as royal palace, prison, armoury, treasury, menagerie, and mint. <span class="highlight">The Princes in the Tower — Edward V and his brother Richard — were last seen playing in the gardens in 1483</span> before vanishing forever, almost certainly murdered on the orders of Richard III. Anne Boleyn, Catherine Howard, Lady Jane Grey, and Sir Walter Raleigh all met their ends here. The Crown Jewels have been stored in the Tower since 1303, when they were nearly stolen from Westminster Abbey.</p>'
  about3 = '<p>The Tower''s ravens are its most famous residents — legend holds that if the ravens ever leave, <span class="highlight">the kingdom will fall</span>. The Ravenmaster, a Yeoman Warder, clips one wing of each bird to ensure they stay. The Yeoman Warders themselves — ''Beefeaters'' — are all retired senior non-commissioned officers from the armed forces. The Ceremony of the Keys, the nightly locking-up ritual, has been performed without interruption for over 700 years.</p>'
  photoBreakQuote = '"Prison, palace, and treasure house — where the crown is kept and kings were unmade."'
}

"leeds-castle" = @{
  narrativeQuote = '"In 1321, Queen Isabella — ''the She-Wolf of France'' — arrived at Leeds Castle demanding entry. The castle''s constable refused and fired on her party, killing six of her men. Her husband Edward II besieged the castle, hanged the constable, and from that day declared Leeds Castle a royal residence for the queens of England."'
  about1 = '<p class="drop-cap">Leeds Castle appears to float — a pale stone dream rising from its own reflection on two islands in a Kentish lake. <span class="highlight">It has been called ''the loveliest castle in the world''</span>, and on a still morning, with mist lifting from the water and swans tracing slow circles, the title seems modest.</p>'
  about2 = '<p>Originally a Saxon manor, the stone castle was built by the Norman baron Robert de Crevecoeur in 1119. It passed to the crown in 1278 and became <span class="highlight">a cherished residence for six medieval queens of England</span>, including Eleanor of Castile and Catherine de Valois. Henry VIII transformed it into a magnificent Tudor palace and used it as a stopping point on his way to the Field of the Cloth of Gold in 1520. After centuries in private hands, the castle was bought by the Anglo-American heiress Lady Baillie in 1926, who spent decades restoring it with impeccable taste.</p>'
  about3 = '<p>Lady Baillie left the castle to a charitable trust, and today it operates as one of Kent''s premier visitor attractions. <span class="highlight">The yew maze, with an underground grotto at its centre, delights children and adults alike.</span> The castle grounds include an aviary with over 100 species, a Dog Collar Museum (the only one in the world), and 500 acres of parkland landscaped by Capability Brown.</p>'
  photoBreakQuote = '"Six queens called this floating castle home. The swans still keep court on the lake below."'
}

"corfe-castle" = @{
  narrativeQuote = '"In 1643, Lady Bankes defended Corfe Castle against a Parliamentarian siege with a garrison of just five men and her maidservants, pouring hot embers and stones onto the attackers. She held out for six weeks. When the castle finally fell in 1646 — betrayed from within — Parliament ordered it ''slighted'': blown apart so thoroughly that its towers now lean at impossible angles."'
  about1 = '<p class="drop-cap">You see Corfe from miles away — <span class="highlight">a shattered crown of stone on a perfect cone of chalk</span>, the gap in the Purbeck Hills framing it like a stage set. It is arguably the most dramatic castle ruin in England, its broken towers tilting at angles that seem to defy gravity, frozen in the moment of their destruction.</p>'
  about2 = '<p>The castle was built by William the Conqueror to guard the only route through the Purbeck Hills. <span class="highlight">In 978 AD, the young King Edward the Martyr was murdered here</span> — stabbed while drinking a cup of mead offered by his stepmother, who wanted the throne for her own son Ethelred. The Normans built the massive keep and curtain walls, and King John used the castle as a treasury and prison — twenty-two French nobles were reportedly starved to death in the dungeons.</p>'
  about3 = '<p>The ruins are now owned by the National Trust, and the village of Corfe Castle — all grey Purbeck stone cottages — clusters at the foot of the mound like something from a storybook. <span class="highlight">The Swanage Railway steam train stops at Corfe Castle station</span>, making it one of the most atmospheric arrivals at any English heritage site. The views from the ruined keep stretch across the Isle of Purbeck to Poole Harbour and the sea.</p>'
  photoBreakQuote = '"Blown apart by Parliament, betrayed from within — and still the most dramatic silhouette in Dorset."'
}

"castle-howard" = @{
  narrativeQuote = '"When the 3rd Earl of Carlisle commissioned Castle Howard in 1699, he chose as his architect a man who had never designed a building: the playwright John Vanbrugh, whose previous career highlight was writing The Provoked Wife. The result was one of the greatest Baroque houses in Europe."'
  about1 = '<p class="drop-cap">The approach is calculated to overwhelm. You pass through Vanbrugh''s monumental archway, drive for a mile through parkland, and then the house appears — <span class="highlight">a Baroque eruption of dome, colonnades, and golden stone</span>, sitting in a landscape so perfectly composed it feels painted rather than planted.</p>'
  about2 = '<p>Castle Howard took over 100 years to complete. Vanbrugh and his assistant Nicholas Hawksmoor created the garden front — <span class="highlight">that astonishing dome, the first on a private house in England</span>, rising above a Great Hall painted by Antonio Pellegrini. In 1940, a devastating fire destroyed the dome and twenty rooms; the house stood open to the sky for twenty years before restoration began. The grounds contain Hawksmoor''s Mausoleum, considered one of the finest funerary buildings in Europe, and Vanbrugh''s Temple of the Four Winds.</p>'
  about3 = '<p>Castle Howard is forever linked with Brideshead Revisited — both the 1981 television series and the 2008 film used it as the fictional Brideshead. <span class="highlight">The Long Gallery houses one of the finest private art collections in the North of England</span>, including works by Holbein, Rubens, and Canaletto. The house remains home to the Howard family, and the Christmas and summer programmes draw visitors from across the world.</p>'
  photoBreakQuote = '"A playwright''s first building — and one of the most beautiful houses on earth."'
}

"alnwick-castle" = @{
  narrativeQuote = '"When the first Harry Potter film crew arrived at Alnwick in 2000, the Duchess of Northumberland insisted they use real owls for the Hogwarts scenes. The production''s owl handler later told her that one of the birds had flown off with a prosthetic finger belonging to a crew member and deposited it on the castle battlements."'
  about1 = '<p class="drop-cap">Alnwick Castle rises from the Northumberland countryside with a stern grandeur that makes its second career as Hogwarts feel inevitable. <span class="highlight">This is the second-largest inhabited castle in England</span> — after Windsor — and the Percy family have called it home since 1309, making it one of the longest continuous aristocratic occupations in the country.</p>'
  about2 = '<p>The first castle was built shortly after the Norman Conquest, but it was <span class="highlight">the Percy family who transformed it into the powerhouse of the North</span>. Harry ''Hotspur'' Percy — immortalised by Shakespeare in Henry IV — launched his ill-fated rebellion against the king from these walls. The 4th Duke remodelled the interior in an extraordinary Italian Renaissance style in the 1850s, importing Roman mosaics and Venetian paintings. The stone figures on the battlements — medieval soldiers in various poses — were added in the 18th century to make the castle look more formidable from a distance.</p>'
  about3 = '<p>The adjacent Alnwick Garden, created by the current Duchess, is a destination in its own right — <span class="highlight">the Poison Garden, behind locked gates, contains some of the deadliest plants in the world</span>, including hemlock, ricin, and cannabis. Broomstick-flying lessons on the castle grounds are wildly popular with younger visitors. The state rooms house one of the finest collections of Venetian paintings outside Italy.</p>'
  photoBreakQuote = '"Home of Hotspur, stand-in for Hogwarts — and the stone soldiers on the battlements are still keeping watch."'
}

"dunnottar-castle" = @{
  narrativeQuote = '"In 1652, as Cromwell''s army besieged Dunnottar, Christian Fletcher — wife of the Reverend James Granger, minister of nearby Kinneff — smuggled the Scottish Crown Jewels out from under the English guns. By one account she carried them hidden in sacks of flax over three visits; by another they were lowered in a creel of seaweed onto the beach below. Either way, the Honours of Scotland survived — and remained hidden beneath the floor of Kinneff Church until the Restoration."'
  about1 = '<p class="drop-cap">The path down from the cliff and back up to the castle entrance is steep, muddy, and magnificent. <span class="highlight">Dunnottar occupies a flat-topped sea stack connected to the mainland by the narrowest of necks</span>, its ruined walls dropping sheer into the North Sea on three sides. On a grey day, with spray coming off the rocks, it feels like the edge of the known world.</p>'
  about2 = '<p>A Pictish fort stood here as early as the 5th century, and William Wallace burned an English garrison alive within the castle''s church in 1297. <span class="highlight">The Whigs'' Vault, a dark and airless cellar, held 167 Covenanting prisoners in 1685</span> — men and women crammed together in conditions so horrific that many died, and those who tried to escape down the cliffs were recaptured and had their hands branded with hot irons. The castle was also the last place in mainland Scotland to hold out against Cromwell, thanks in part to Christian Fletcher''s daring rescue of the Crown Jewels.</p>'
  about3 = '<p>Today, Dunnottar is a privately owned ruin that requires a bracing walk from the car park along the clifftop. <span class="highlight">The panoramic views from the ruined tower house stretch along the Aberdeenshire coast in both directions.</span> The War Memorial within the castle grounds commemorates local men lost in both World Wars. Franco Zeffirelli used Dunnottar as a location for his 1990 film of Hamlet, starring Mel Gibson.</p>'
  photoBreakQuote = '"The minister''s wife walked out with a nation''s crown jewels in a sack of flax. The English never knew."'
}

"eilean-donan-castle" = @{
  narrativeQuote = '"In 1719, a small garrison of Spanish soldiers — sent to support a Jacobite rising — held Eilean Donan against three Royal Navy frigates. HMS Worcester, HMS Flamborough, and HMS Enterprise bombarded the castle for three days, then sent a landing party that found 343 barrels of gunpowder. They blew the castle to rubble. It lay in ruins for two centuries."'
  about1 = '<p class="drop-cap">The image is so iconic it barely needs introduction: <span class="highlight">a stone castle on a tiny island where three sea lochs converge</span>, backed by the peaks of Kintail, connected to the mainland by a curving stone bridge. Eilean Donan is arguably the most photographed castle in Scotland — and possibly the most romantic ruin ever rebuilt.</p>'
  about2 = '<p>A fortification has stood on this island since the 6th century, when it may have been used by the Pictish saint Donnán of Eigg. The castle as it existed was built in the 13th century and became a stronghold of <span class="highlight">the Clan Mackenzie and their allies the Clan MacRae</span>. After its destruction by the Royal Navy in 1719, the castle lay in ruins until Lt Colonel John MacRae-Gilstrap bought the island in 1911 and spent twenty years painstakingly rebuilding it — using the original plans discovered in Edinburgh. The reconstruction was completed in 1932.</p>'
  about3 = '<p>The castle has appeared in countless films, from Highlander to The World Is Not Enough. <span class="highlight">The Banqueting Hall contains a remarkable collection of Jacobite memorabilia and clan artefacts.</span> The drive along Loch Duich to reach it is one of the most scenic in Scotland. Visit on a still day and the castle''s reflection in the loch doubles the magic.</p>'
  photoBreakQuote = '"Destroyed by three frigates, rebuilt from memory, and now the most photographed castle in Scotland."'
}

"conwy-castle" = @{
  narrativeQuote = '"Edward I built Conwy Castle in just four years and five months — an almost superhuman feat of medieval engineering. At its peak, 1,500 men worked the site simultaneously, and the cost of £15,000 would have funded a small war. Master James of St George, the architect, called it his finest work."'
  about1 = '<p class="drop-cap">Conwy Castle is a bruiser. Where some medieval fortresses charm, Conwy intimidates — <span class="highlight">eight massive drum towers connected by curtain walls of such thickness they seem carved from the rock itself</span>. It sits at the mouth of the River Conwy, perfectly positioned to control the coastal route into North Wales.</p>'
  about2 = '<p>Edward I commissioned the castle in 1283 as part of his ''Iron Ring'' — a chain of fortresses designed to subjugate Wales permanently. <span class="highlight">The castle withstood a siege by the Welsh prince Madog ap Llywelyn in the bitter winter of 1294-95</span>, when Edward himself was trapped inside with dwindling supplies. Richard II sheltered here in 1399 before being tricked into surrendering to Henry Bolingbroke, ending the Plantagenet line. In 1401, Welsh rebels under the brothers Rhys and Gwilym ap Tudur captured the castle on Good Friday, when the garrison of just fifteen men were at church.</p>'
  about3 = '<p>The castle and town walls together form a UNESCO World Heritage Site. <span class="highlight">Conwy''s town walls are the most complete medieval town defences in Britain</span>, stretching over three-quarters of a mile with 21 towers and three original gateways. The views from the castle''s battlements take in Snowdonia, the Conwy estuary, and Thomas Telford''s elegant suspension bridge. The Smallest House in Great Britain sits on the quay below.</p>'
  photoBreakQuote = '"Eight towers, four years, fifteen hundred men — Edward I''s iron will made stone."'
}

"cardiff-castle" = @{
  narrativeQuote = '"In the 1860s, the 3rd Marquess of Bute — at twenty-one the richest man in the world — hired the eccentric architect William Burges to transform a crumbling Norman castle into a Victorian Gothic fantasy. Burges filled every surface with gold leaf, carved animals, painted ceilings, and stained glass. He died before finishing. The Marquess completed the work as a memorial to his genius."'
  about1 = '<p class="drop-cap">Cardiff Castle is three buildings pretending to be one. At its heart, <span class="highlight">a Norman keep sits atop a Roman fort</span>, the ancient motte surrounded by 2,000-year-old walls. But look up from the courtyard and something entirely different emerges — a riot of Victorian Gothic fantasy, all spires and clock towers, that looks like it belongs in a fairy tale.</p>'
  about2 = '<p>The Romans built a fort here around 55 AD, and sections of their wall — rebuilt in the 3rd century — still stand within the castle grounds. The Normans added the motte and keep in the 1080s. But it was the extraordinary partnership between the <span class="highlight">3rd Marquess of Bute and the architect William Burges that created the castle''s most remarkable rooms</span>. The Arab Room, with its muqarnas ceiling entirely covered in gold leaf, is one of the most extraordinary Victorian interiors in Britain. The Banqueting Hall, the Library, and the Nursery are each a complete artistic universe — every surface encrusted with symbolic carvings, painted scenes, and jewel-like stained glass.</p>'
  about3 = '<p>The castle sits in the heart of Cardiff, its grounds forming Bute Park — a green corridor stretching along the River Taff. <span class="highlight">The wartime tunnels beneath the castle walls sheltered thousands of Cardiff residents during the Blitz.</span> The Norman Keep offers panoramic views over the city, and the castle hosts regular events including outdoor cinema and the Cardiff Castle Christmas Market.</p>'
  photoBreakQuote = '"Roman walls, a Norman keep, and a Victorian madman''s golden dream — all in the heart of Cardiff."'
}

"blarney-castle" = @{
  narrativeQuote = '"When Queen Elizabeth I demanded that Cormac MacDermot MacCarthy, Lord of Blarney, surrender his castle and lands, he responded with such elaborate, flattering, and ultimately meaningless letters that the exasperated queen finally declared: ''This is all Blarney — what he says, he never means.'' And so the word entered the English language."'
  about1 = '<p class="drop-cap">Blarney Castle is wilder than you expect. The tower house rises from a tangle of ancient trees, <span class="highlight">its battlements crusted with ferns and its base wrapped in poisonous gardens</span>. This is not a manicured heritage experience — it''s a medieval stronghold slowly being reclaimed by nature, and all the more atmospheric for it.</p>'
  about2 = '<p>The MacCarthy dynasty built the current tower in 1446, though a stone castle has stood here since the 13th century. <span class="highlight">The Blarney Stone, set in the battlements just below the parapet, has been drawing visitors since the 18th century</span> — you must lean backwards over a sheer drop to kiss it, held by an attendant. Legend attributes its power to various sources: a gift from Robert the Bruce, a fragment of the Stone of Scone, or a stone brought back from the Crusades. Whatever the truth, an estimated 400,000 people a year make the climb and lean back into the void.</p>'
  about3 = '<p>The castle grounds are as compelling as the tower. <span class="highlight">The Poison Garden contains wolfsbane, mandrake, and opium poppies behind wrought-iron cages.</span> The Rock Close — a mysterious arrangement of ancient stones and trees — includes a Witch''s Kitchen, a Druid''s Circle, and Wishing Steps that must be descended backwards with your eyes closed. The Fern Garden and the lake walk make Blarney one of the finest garden experiences in Ireland.</p>'
  photoBreakQuote = '"What he says, he never means — and the word that a queen coined is still drawing the world to this tower."'
}

"rock-of-cashel" = @{
  narrativeQuote = '"According to legend, the Rock of Cashel was formed when St Patrick banished Satan from a cave in the Devil''s Bit Mountain twenty miles to the north. The devil took a bite out of the mountain as he fled — that gap is still visible today — and spat the rock onto the plain at Cashel. The geology, admittedly, tells a different story."'
  about1 = '<p class="drop-cap">The Rock rises from the Tipperary plain like a hallucination — <span class="highlight">a cluster of medieval towers, cathedral walls, and round towers perched on a limestone outcrop</span> that seems deliberately placed by a higher power. On a misty morning, with sheep grazing the fields below and the silhouettes of ruined arches against the sky, it is one of the most hauntingly beautiful sites in Ireland.</p>'
  about2 = '<p>This was the seat of the Kings of Munster for over 400 years before being granted to the Church in 1101. <span class="highlight">Cormac''s Chapel, consecrated in 1134, is the jewel of Irish Romanesque architecture</span> — a tiny, exquisite building with carved tympana, a stone-roofed nave, and fragments of the oldest surviving frescoes in Ireland. The Gothic cathedral, roofless since the burning of 1495, rises beside it. The round tower, dating from around 1100, is the oldest structure on the Rock. The Hall of the Vicars Choral, with its medieval fireplace, is the only fully roofed building remaining.</p>'
  about3 = '<p>The Rock is managed by the Office of Public Works and is one of Ireland''s most-visited heritage sites. <span class="highlight">The high crosses and carved tombstones in the graveyard span a thousand years of Irish history.</span> The town of Cashel below — sometimes called the ''Golden Vale'' — is a pleasant market town with good pubs and the Bru Boru cultural centre, which hosts traditional Irish music and dance.</p>'
  photoBreakQuote = '"The Devil spat this rock from his mouth. St Patrick claimed it for God. A thousand years of prayers soaked into the stone."'
}

"kilkenny-castle" = @{
  narrativeQuote = '"In 1967, the 6th Marquess of Ormonde sold Kilkenny Castle to the people of the city for £50. The Butler family had owned it for 581 years. When asked why he sold it so cheaply, he reportedly said he could no longer afford the roof repairs."'
  about1 = '<p class="drop-cap">Kilkenny Castle presides over its medieval city with the quiet authority of a family patriarch — <span class="highlight">its pale limestone towers reflected in the River Nore</span>, its parkland rolling down to the water''s edge. It is a castle that has been lived in, fought over, neglected, and lovingly restored, and each chapter shows.</p>'
  about2 = '<p>Strongbow''s son-in-law William Marshal built the first stone castle here around 1204, establishing the classic four-towered layout. <span class="highlight">The Butler family — Earls, Marquesses, and Dukes of Ormonde — made it their seat from 1391 until 1967</span>, a span of nearly six centuries. The castle endured multiple sieges during the Confederate and Cromwellian wars of the 1640s. In the 1840s, the Butlers undertook a major Victorian Gothic revival restoration, creating the spectacular Long Gallery — a double-height hall with a painted ceiling, Pre-Raphaelite-style portraits, and a hammer-beam roof.</p>'
  about3 = '<p>After the £50 sale, the Irish state spent decades restoring the castle to its Victorian splendour. <span class="highlight">The Long Gallery, with its painted ceiling and collection of Butler family portraits, is the undisputed highlight.</span> The parkland — free to enter — is the green heart of Kilkenny, popular with locals for walks along the Nore. The Butler Gallery, housed in the castle basement, shows contemporary Irish art in medieval surroundings. The castle hosts regular craft fairs and the annual Kilkenny Arts Festival.</p>'
  photoBreakQuote = '"Five hundred and eighty-one years of one family, sold for fifty pounds — and reborn as a city''s treasure."'
}

}

# Now process each castle
foreach ($slug in $castles.Keys) {
    $file = Join-Path $sitePath "$slug.html"
    if (-not (Test-Path $file)) {
        Write-Host "SKIP: $file not found"
        continue
    }
    
    $content = Get-Content $file -Raw
    $data = $castles[$slug]
    
    # 1. Replace narrative quote
    # Pattern: <div class="narrative-quote">\s*<p>"...anything..."</p>\s*</div>
    $content = $content -replace '(<div class="narrative-quote">\s*<p>)"[^"]*\.?"(</p>\s*</div>)', "`$1$($data.narrativeQuote)`$2"
    
    # 2. Replace About section - find from <h2>About</h2> to <div id="hoursInline"
    # We need to replace everything between <h2>About</h2> and <div id="hoursInline"
    $aboutReplacement = @"
<h2>About</h2>
      $($data.about1)
      $($data.about2)
      $($data.about3)
      
"@
    $content = $content -replace '<h2>About</h2>\s*<p class="drop-cap">.*?</p>(?:\s*<p>.*?</p>)*\s*(?=<div id="hoursInline")', $aboutReplacement
    
    # 3. Replace photo break quote
    $content = $content -replace '(<div class="pb-text">\s*<p>)"[^"]*"(</p>\s*</div>)', "`$1$($data.photoBreakQuote)`$2"
    
    Set-Content -Path $file -Value $content -NoNewline
    Write-Host "DONE: $slug"
}

Write-Host "`nAll enrichments complete!"
